// This file is generated by build.rs, do not modify

use crate::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 52] = [
    // account_get_initial_commitment
    word!("0x0a0cb376021c606c618d248b00d0f545dbf02968110581d3dba88ecd75b27476"),
    // account_compute_commitment
    word!("0xbd0a999fa0d7459f66a3bb55729ada356a5960bb09455c5267783b95106f54fd"),
    // account_get_id
    word!("0x2fe44dda4696de30933a570b0e38185cf7f534919bc5023a613964e1883c9ba5"),
    // account_get_nonce
    word!("0xbef896156a1ab68fcd12f66acff8efd0c2dafaad4d723e6b76a791d332a4c3f8"),
    // account_incr_nonce
    word!("0x4af3a56605017c3e0ee5c6f8e38c903525510759a520cec5e014b766235623c3"),
    // account_get_code_commitment
    word!("0xd81f394cb954d89d2fda9733a843ae657c734dead1c7f59033a445e4829bebe0"),
    // account_get_initial_storage_commitment
    word!("0xb20cce8817acaee05270eb43ad3e8808240d09151a83118ea9f63323dd4bc5a9"),
    // account_compute_storage_commitment
    word!("0xcd487d8920b27ac62748649798e2de553d899c027902a5daa2df78ff8bed5a58"),
    // account_get_item
    word!("0xc1de1e50015036b76c3bab95aa8b2e285c1dec1be502d7141e7cde73cf1f59f8"),
    // account_get_initial_item
    word!("0xff00384d8ac2104a5f574d14dca1361871467d46dc194c4cf4a233532aed2325"),
    // account_set_item
    word!("0xdd160e6ac0053e729d485f69bd45ebd1ac1f3d5463cee5b4e377af88cf722978"),
    // account_get_map_item
    word!("0xe464452d50007452c08a60017447fe8df61268c06e62b30ac04b43e7fdae2c84"),
    // account_get_initial_map_item
    word!("0x212d35e9e9f9a9efb2345ab4553f3fd554c74946f961e91a7464a935bd6bf867"),
    // account_set_map_item
    word!("0x34845f24e0f9ba9118d54963a07a7b27554517da281c01d3f981231cca9b2e09"),
    // account_get_initial_vault_root
    word!("0x894c494ea1fcf10a58075c60490607c54f66ec4af6f77c1320c3e6ed2a11cb40"),
    // account_get_vault_root
    word!("0x1e3d8f19d76a87777ca8e07774b5e99c7fd20e51ff834a9f531ca0bde82ed269"),
    // account_add_asset
    word!("0x133a2206c11f843fc0a5e4f234fad60982014bf91db1e29197fcee2c08b1415f"),
    // account_remove_asset
    word!("0x5ba6a99e374cd8861447b40be9d1235af3c4bfe9f793b7fc79f4ed13f6770812"),
    // account_get_balance
    word!("0xc4bbc38bf2f239397c9c4aec9ffb415068c5e047f6d3bb36c73cb04e6abe661a"),
    // account_get_initial_balance
    word!("0xf5987b8e8ab1b6c47cc0e6ef7b3ab3b346fc362dd208ff01060234debc718535"),
    // account_has_non_fungible_asset
    word!("0x3781397f32da1b58b79757828ccfc3f5e02d4a9e314dcdea85d2648eaca51a21"),
    // account_compute_delta_commitment
    word!("0xace0339a8c2bd076e64721f26b11f305851a7b54f36a58a965cd5dc2dbde0b54"),
    // account_get_num_procedures
    word!("0xf633ec7d9776c462ada535bf44fea0602f16d0a6bb6ca58265f0c4867e2647b6"),
    // account_get_procedure_root
    word!("0x693054519dd35a4106094fb6d5ee1e5f0a6b5b61a9c9c3f3089076093215d9ce"),
    // account_was_procedure_called
    word!("0x701f535bbf646f8e59dd0b05dad2ba5228265f267481f6103ce5addeece28cb7"),
    // account_has_procedure
    word!("0xfb2687afc69061527c6583c52597949e99a28e1444dde349ce8f6cb00be2062e"),
    // faucet_mint_asset
    word!("0x72872254c8b5332ac42c7cd31e2a84238b983267264cf51e3a997e2c3cdd4073"),
    // faucet_burn_asset
    word!("0x617e456e768ceb617888766a7df051711aa69b6d1c395bd024b2fba7ba42ad62"),
    // faucet_get_total_fungible_asset_issuance
    word!("0x7ad6d6123df1028cc10a6f4cd3a4c7f5cd6218ac125bccd86bd54a53f9e61774"),
    // faucet_is_non_fungible_asset_issued
    word!("0xc8be2dc5e233f0823329f0106cd7efa5ef8c1ad1fff547d00532a1cb00d5059e"),
    // input_note_get_metadata
    word!("0x00054c4b097adae656b7d7a7721425d91a1923164bf16b1cab83c730807944e1"),
    // input_note_get_assets_info
    word!("0xa94da7f1c6722aa52db958e026afb58d7850e9c208c18aab3922335985160bba"),
    // input_note_get_script_root
    word!("0x6a21328aff9dcfc3d671eca4fd12e991f4f6046447c2cda0fcf640f94b2e4d28"),
    // input_note_get_inputs_info
    word!("0xe7c25deb5c505b34c7e40bd31d284a01a842250c87b787807f7c49d5bbd10e0e"),
    // input_note_get_serial_number
    word!("0xf3caf62d39561978c7c486680afe80a60abe0285d815de1bf9392a97c6c5312a"),
    // input_note_get_recipient
    word!("0xcb486b16e78907161dda464e7f8ab4ce05d55b78d2f1d0af7dba32b20b842cc0"),
    // output_note_create
    word!("0x433eac69a353da131f0ade3047f1d8031e9119e274c41564e7900f6230f705b9"),
    // output_note_get_metadata
    word!("0x3536347c35d038e03ae573a13fe44ef800452617f3ff905a0be32161f35092b0"),
    // output_note_get_assets_info
    word!("0x62c4e2ae2b7f8ade59fa0b76e53f65f069145fdbe0e02eface1ec16d85a44cd3"),
    // output_note_get_recipient
    word!("0x27240d1c0a13262f6439be45b0d2463e24b49787206cc2164348e971416bf74a"),
    // output_note_add_asset
    word!("0x4d59b0b29b3aa1e70c860fd8281090c3d251cf8778e6797cc4dff09237aa030c"),
    // tx_get_num_input_notes
    word!("0x93fd1eb66b1a58ed838fccaa50dc30959db29374147c7098d71f3dca0f738658"),
    // tx_get_input_notes_commitment
    word!("0x058053d92217a737890ac97d998566eabe8e4c6010c4841968b07959a7df3fa2"),
    // tx_get_num_output_notes
    word!("0xfd1ec808e4ebd96cb1d9e16995c97c484277b6dfb88e327d1033e89d2efb5b10"),
    // tx_get_output_notes_commitment
    word!("0x7933fc7205e83eb5cac49a8f6bd2d0d33253a2fcd3240de5cde7648b6eaa2ac8"),
    // tx_get_block_commitment
    word!("0x5dd1af16a7175966a53ebba2550351be66d79bc2d3b70cb1af1522f128dbcf23"),
    // tx_get_block_number
    word!("0xde7cfd5058cae688bb6416ee3bea18f7d2296f6077bd9e88aab67ec0d170eaf8"),
    // tx_get_block_timestamp
    word!("0xa04c1588d66348e0bf98003479b61da556714ffa0c70344b0d89a68aa16fb613"),
    // tx_start_foreign_context
    word!("0x13023048d43a5213903736117dca1b5700782caf781f8cc16a363eae4d4dcd44"),
    // tx_end_foreign_context
    word!("0x23dc130183c87f7537c56aad50533cbcb16fbca5d71a17d7655572dfa1b1baab"),
    // tx_get_expiration_delta
    word!("0xbffe80441afba3fea6441d094d87012da55c5dacd5d280db749b74f5e8a10cf8"),
    // tx_update_expiration_block_delta
    word!("0xd681ec53d6a3df1dc1702ab9dd46bcea3830d6f590b9385ccc88583e87ab15fd"),
];

/// Names of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURE_NAMES: [&str; 52] = [
    // account_get_initial_commitment
    "account_get_initial_commitment",
    // account_compute_commitment
    "account_compute_commitment",
    // account_get_id
    "account_get_id",
    // account_get_nonce
    "account_get_nonce",
    // account_incr_nonce
    "account_incr_nonce",
    // account_get_code_commitment
    "account_get_code_commitment",
    // account_get_initial_storage_commitment
    "account_get_initial_storage_commitment",
    // account_compute_storage_commitment
    "account_compute_storage_commitment",
    // account_get_item
    "account_get_item",
    // account_get_initial_item
    "account_get_initial_item",
    // account_set_item
    "account_set_item",
    // account_get_map_item
    "account_get_map_item",
    // account_get_initial_map_item
    "account_get_initial_map_item",
    // account_set_map_item
    "account_set_map_item",
    // account_get_initial_vault_root
    "account_get_initial_vault_root",
    // account_get_vault_root
    "account_get_vault_root",
    // account_add_asset
    "account_add_asset",
    // account_remove_asset
    "account_remove_asset",
    // account_get_balance
    "account_get_balance",
    // account_get_initial_balance
    "account_get_initial_balance",
    // account_has_non_fungible_asset
    "account_has_non_fungible_asset",
    // account_compute_delta_commitment
    "account_compute_delta_commitment",
    // account_get_num_procedures
    "account_get_num_procedures",
    // account_get_procedure_root
    "account_get_procedure_root",
    // account_was_procedure_called
    "account_was_procedure_called",
    // account_has_procedure
    "account_has_procedure",
    // faucet_mint_asset
    "faucet_mint_asset",
    // faucet_burn_asset
    "faucet_burn_asset",
    // faucet_get_total_fungible_asset_issuance
    "faucet_get_total_fungible_asset_issuance",
    // faucet_is_non_fungible_asset_issued
    "faucet_is_non_fungible_asset_issued",
    // input_note_get_metadata
    "input_note_get_metadata",
    // input_note_get_assets_info
    "input_note_get_assets_info",
    // input_note_get_script_root
    "input_note_get_script_root",
    // input_note_get_inputs_info
    "input_note_get_inputs_info",
    // input_note_get_serial_number
    "input_note_get_serial_number",
    // input_note_get_recipient
    "input_note_get_recipient",
    // output_note_create
    "output_note_create",
    // output_note_get_metadata
    "output_note_get_metadata",
    // output_note_get_assets_info
    "output_note_get_assets_info",
    // output_note_get_recipient
    "output_note_get_recipient",
    // output_note_add_asset
    "output_note_add_asset",
    // tx_get_num_input_notes
    "tx_get_num_input_notes",
    // tx_get_input_notes_commitment
    "tx_get_input_notes_commitment",
    // tx_get_num_output_notes
    "tx_get_num_output_notes",
    // tx_get_output_notes_commitment
    "tx_get_output_notes_commitment",
    // tx_get_block_commitment
    "tx_get_block_commitment",
    // tx_get_block_number
    "tx_get_block_number",
    // tx_get_block_timestamp
    "tx_get_block_timestamp",
    // tx_start_foreign_context
    "tx_start_foreign_context",
    // tx_end_foreign_context
    "tx_end_foreign_context",
    // tx_get_expiration_delta
    "tx_get_expiration_delta",
    // tx_update_expiration_block_delta
    "tx_update_expiration_block_delta",
];
